my_kanban2/urls.py
# from django.contrib import admin
import my_kanban2.settings as settings
from django.urls import include, path
from thisapp import http_handlers

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('thisapp.urls')),
    path('', include('user.urls')),
    path('', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")),)


handler400 = http_handlers.bad_request_view
handler403 = http_handlers.permission_denied_view
handler404 = http_handlers.page_not_found_view

thisapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/invitations/boards/<int:board_id>/', views.pick_invitation_view, name='pick_invitation'),
    path('boards/', views.create_board_view, name='create_board'),
    path('boards/<int:board_id>/', views.handle_board_view, name='board'),
    path('boards/<int:board_id>/invitations/', views.сreate_invitation_view, name='сreate_invitation'),
    path('boards/<int:board_id>/members/', views.delete_member_view, name='delete_member'),
    path('boards/<int:board_id>/cards/', views.create_card_view, name='card_create'),
    path('boards/<int:board_id>/cards/<int:card_id>/', views.handle_card_view, name='card'),
    path('boards/<int:board_id>/cards/<int:card_id>/comments/', views.create_comment_view, name='create_comment'),
    path(
        'boards/<int:board_id>/cards/<int:card_id>/comments/<int:comment_id>/',
        views.delete_comment_view,
        name='delete_comment',
    ),
    path(
        'boards/<int:board_id>/cards/<int:card_id>/comments/<int:comment_id>/file',
        views.get_file_from_comment,
        name='get_file_from_comment',
    ),
]

user/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetDoneView)
from django.urls import path

from . import OAuth2, views

urlpatterns = [
    path('signup/', views.RegisterUserView.as_view(), name='signup'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/redirect-to-OAuth2/select-<str:provider>/', OAuth2.logout_then_OAuth2, name='logout_then_OAuth2'),
    path('password-change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path(
        'password-change/done/',
        PasswordChangeDoneView.as_view(template_name='user/password_change_done.html'),
        name='password_change_done'
    ),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password-reset/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password-reset/complete/',
        PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

thisapp/models.py
import os

from django.db import models

from thisapp.validators import validate_file_size
from user.models import CustomUser


class Board(models.Model):
    title = models.CharField(max_length=32)
    members = models.ManyToManyField(CustomUser, through="Membership")

    def __str__(self):
        return self.title


class Membership(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    is_owner = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.user.username} in {self.board.title}'


class Card(models.Model):
    class Status(models.IntegerChoices):
        BACKLOG = 1, 'Backlog'
        IN_PROGRESS = 2, 'In progress'
        DONE = 3, 'Done'

    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='cards')
    title = models.TextField()
    content = models.TextField(blank=True, null=True)
    status = models.IntegerField(choices=Status.choices, default=Status.BACKLOG)

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='own_comments')
    content = models.TextField()
    date = models.DateTimeField(auto_now=True)
    file = models.FileField(
        upload_to='user_uploads',
        validators=[validate_file_size],
        default=None,
        null=True,
        blank=True,
    )

    def __str__(self) -> str:
        return str(self.card)

    def get_filename(self) -> str | None:
        if self.file:
            return os.path.basename(self.file.path)

    def delete(self, *args, **kwargs):
        if self.file:
            os.remove(self.file.path)
        super().delete(*args, **kwargs)

thisapp/forms.py
from django import forms

from .models import Board, Card, Comment


class CreateBoardForm(forms.ModelForm):
    ...

    class Meta:
        model = Board
        fields = ['title']


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['title', 'content']
        widgets = {
            'title': forms.Textarea(attrs={'class': 'card-title', 'placeholder': 'Enter title', 'required': True}),
            'content': forms.Textarea(attrs={'class': 'card-content', 'placeholder': 'Enter content'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'file']
        labels = {
            'file': 'Upload the file up to 50 MB.'
        }
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'comment-input',
                'placeholder': 'Enter a comment',
                'required': True}
            )
        }

thisapp/views.py
import mimetypes
from collections import defaultdict

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import BadRequest, PermissionDenied
from django.db import transaction
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
                              render)
from django.urls import reverse

from thisapp.http_handlers import custom_require_http_methods
from user.models import CustomUser

from . import utils
from .forms import CardForm, CommentForm, CreateBoardForm
from .models import Board, Card, Comment, Membership


@custom_require_http_methods(['GET'])
def index_view(request):
    return render(request, 'index.html')


@login_required
@custom_require_http_methods(['GET'])
def profile_view(request):
    user_boards = Membership.objects.filter(user=request.user).select_related('board')

    boards = defaultdict(list)
    for user in user_boards:
        if user.is_owner:
            boards['owner boards'].append(user.board)
        else:
            boards['invitation boards'].append(user.board)

    context = {
        'form': CreateBoardForm(),
        'owner_boards': boards['owner boards'],
        'invitation_boards': boards['invitation boards'],
        'invitations': utils.get_user_invitations(request.user.username),
    }
    return render(request, 'profile.html', context=context)


@login_required
@custom_require_http_methods(['GET', 'POST'])
def handle_board_view(request, board_id):
    board = get_object_or_404(
        Board.objects.prefetch_related('membership_set__user', 'cards'),
        id=board_id,
    )

    user = request.user
    user_with_board = Membership.objects.filter(user=user, board=board).first()

    if not user_with_board:
        raise PermissionDenied

    if request.method == 'POST':
        if not user_with_board.is_owner:
            raise PermissionDenied
        else:
            board.delete()
            utils.delete_board_invitations(board_id)
            return redirect('profile')

    grouped_cards = defaultdict(list)
    for card in board.cards.all():
        grouped_cards[card.status].append(card)

    context = {
        'board': board,
        'user_is_owner': user_with_board.is_owner,
        'backlog_cards': grouped_cards.get(Card.Status.BACKLOG, []),
        'in_progress_cards': grouped_cards.get(Card.Status.IN_PROGRESS, []),
        'done_cards': grouped_cards.get(Card.Status.DONE, []),
    }
    return render(request, 'board.html', context=context)


@login_required
@custom_require_http_methods(['POST'])
def create_board_view(request):
    form = CreateBoardForm(request.POST)

    if not form.is_valid():
        for field, list_error in form.errors.items():
            for error in list_error:
                messages.error(request, field + ': ' + error)
        raise BadRequest

    with transaction.atomic():
        board = form.save()
        Membership.objects.create(
            user=request.user,
            board=board,
            is_owner=True
        )
    return HttpResponseRedirect(reverse('profile'), status=303)


@login_required
@custom_require_http_methods(['POST'])
def сreate_invitation_view(request, board_id):
    membership = get_list_or_404(Membership, board=board_id)
    sender = request.user

    if not any(m.is_owner and m.user == sender for m in membership):
        raise PermissionDenied

    recipient_name = request.POST.get('recipient', '')
    recipient = CustomUser.objects.filter(username=recipient_name).first()

    if not recipient:
        messages.error(request, f'User "{recipient_name}" does not exist')
        raise BadRequest

    if any(m.user == recipient for m in membership):
        messages.error(request, f'User "{recipient_name}" is already a member of the board')
        raise BadRequest

    if utils.get_invitation(board_id, recipient_name):
        messages.error(request, f'User "{recipient_name}" has already received an invitation')
        raise BadRequest

    utils.create_invitation(board_id, sender.username, recipient_name)
    messages.success(request, 'The invitation has been sent!')

    response = redirect('board', board_id=board_id)
    response.status_code = 303
    return response


@login_required
@custom_require_http_methods(['POST'])
def delete_member_view(request, board_id):
    membership = get_list_or_404(Membership, board=board_id)

    if not any(m.is_owner for m in membership if m.user == request.user):
        raise PermissionDenied

    member_name = request.POST.get('member', '')
    member = CustomUser.objects.filter(username=member_name).first()

    if not member or all(m.user != member for m in membership if not m.is_owner):
        messages.error(request, f'The use of the user "{member_name}" in the request is incorrect')
        raise BadRequest

    Membership.objects.filter(
        user=member,
        board_id=board_id
    ).delete()

    response = redirect('board', board_id=board_id)
    response.status_code = 303
    return response


@login_required
@custom_require_http_methods(['POST'])
def pick_invitation_view(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    user = CustomUser.objects.get(username=request.user)

    if not utils.get_invitation(board.id, user.username):
        messages.error(request, f'The user {user.username} does not have an invitation to the board')
        raise BadRequest

    operation = request.POST.get('operation', '')

    if operation == 'accept':
        Membership.objects.create(
            user=user,
            board_id=board_id
        )
    elif operation == 'reject':
        pass
    else:
        messages.error(request, f'The “{operation}” operation is incorrect in this request')
        raise BadRequest

    utils.delete_invitation(board_id, user.username)

    response = redirect('profile')
    response.status_code = 303
    return response


@login_required
@custom_require_http_methods(['GET', 'POST'])
def create_card_view(request, board_id):
    board = get_object_or_404(Board, id=board_id)

    if not Membership.objects.filter(board=board, user=request.user, is_owner=True).exists():
        raise PermissionDenied

    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.board_id = board_id
            card.save()
            response = redirect('board', board_id=board_id)
            response.status_code = 303
            return response
        else:
            for field, list_error in form.errors.items():
                for error in list_error:
                    messages.error(request, field + ': ' + error)
            raise BadRequest

    context = {
        'board_id': board_id,
        'form': CardForm(),
    }
    return render(request, 'card/create.html', context=context)


def handle_post_request_card(request, card: Card, board: Board, user_with_board: Membership):
    operation = request.POST.get('operation', '')
    errors = {}

    if operation == 'DELETE':
        if not user_with_board.is_owner:
            raise PermissionDenied
        result = utils.delete_card(card)

    elif operation == 'EDIT':
        if not user_with_board.is_owner:
            raise PermissionDenied
        card_form = CardForm(request.POST)
        result, errors = utils.edit_card(card_form, card)

    elif 'MOVE' in operation:
        result = utils.move_card(card, operation)

    else:
        result = False

    if not result:
        if errors:
            for field, list_error in errors.items():
                for error in list_error:
                    messages.error(request, field + ': ' + error)
        else:
            messages.error(request, f'The “{operation}” operation is incorrect in this request')
        raise BadRequest

    response = redirect('board', board_id=board.id)
    response.status_code = 303
    return response


@login_required
@custom_require_http_methods(['GET', 'POST'])
def handle_card_view(request, board_id, card_id):
    board = get_object_or_404(Board, id=board_id)
    card = get_object_or_404(Card.objects.prefetch_related('comments__author'), id=card_id, board=board)
    user_with_board = Membership.objects.filter(board_id=board_id, user=request.user).select_related('user').first()

    if not user_with_board:
        raise PermissionDenied

    if request.method == 'POST':
        return handle_post_request_card(request, card, board, user_with_board)

    comment_form = CommentForm()

    context = {
        'board': board,
        'user_with_board': user_with_board,
        'card': card,
        'comment_form': comment_form,
    }

    if user_with_board.is_owner:
        context['card_form'] = CardForm(instance=card)

    return render(request, 'card/view.html', context=context)


@login_required
@custom_require_http_methods(['POST'])
def create_comment_view(request, board_id, card_id):
    board = get_object_or_404(Board, id=board_id)

    if not Membership.objects.filter(user=request.user, board_id=board_id).exists():
        raise PermissionDenied

    card = get_object_or_404(Card, id=card_id, board=board)
    form = CommentForm(request.POST, request.FILES)

    if not form.is_valid():
        for field, list_error in form.errors.items():
            for error in list_error:
                messages.error(request, field + ': ' + error)
            raise BadRequest

    comment = form.save(commit=False)
    comment.card_id = card.id
    comment.author = request.user
    comment.save()
    return redirect('card', board_id=board_id, card_id=card_id)


@login_required
@custom_require_http_methods(['GET'])
def get_file_from_comment(request, board_id, card_id, comment_id):
    board = get_object_or_404(Board, id=board_id)

    if not Membership.objects.filter(user=request.user, board_id=board_id).exists():

thisapp/templates/board.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
    {% include 'includes/common_head.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'thisapp/css/board.css' %}">
    <title>Board "{{ board.title }}"</title>
</head>

<body>

    <header>
        <form action="{% url 'logout' %}" method="get">
            <button class="transparent-button">Log out</button>
        </form>

        <h1>{{ board.title }}</h1>

        <form action="{% url 'profile' %}" method="get">
            <button class="transparent-button">Profile</button>
        </form>
    </header>

    <main>
        <section class="board">

            <div class="column">
                <h2>Backlog [{{ backlog_cards|length }}]</h2>

                <div class="scrollable">
                    {% for card in backlog_cards %}
                    <div class="card">
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="get"
                            class="flex-grow-rest">
                            <button class="open-card-button">{{ card.title|linebreaksbr }}</button>
                        </form>
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="post"
                            class="flex-20">
                            {% csrf_token %}
                            <input type="hidden" name="operation" value="MOVE_RIGHT">
                            <button class="move-card-button">=&gt;</button>
                        </form>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="column">
                <h2>In progress [{{ in_progress_cards|length }}]</h2>

                <div class="scrollable">
                    {% for card in in_progress_cards %}
                    <div class="card">
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="post"
                            class="flex-20">
                            {% csrf_token %}
                            <input type="hidden" name="operation" value="MOVE_LEFT">
                            <button class="move-card-button">&#60;=</button>
                        </form>
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="get"
                            class="flex-grow-rest">
                            <button class="open-card-button">{{ card.title|linebreaksbr }}</button>
                        </form>
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="post"
                            class="flex-20">
                            {% csrf_token %}
                            <input type="hidden" name="operation" value="MOVE_RIGHT">
                            <button class="move-card-button">=&gt;</button>
                        </form>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="column">
                <h2>Done [{{ done_cards|length }}]</h2>

                <div class="scrollable">
                    {% for card in done_cards %}
                    <div class="card">
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="post"
                            class="flex-20">
                            {% csrf_token %}
                            <input type="hidden" name="operation" value="MOVE_LEFT">
                            <button class="move-card-button">&#60;=</button>
                        </form>
                        <form action="{% url 'card' board_id=board.id card_id=card.id %}" method="get"
                            class="flex-grow-rest">
                            <button class="open-card-button">{{ card.title|linebreaksbr }}</button>
                        </form>
                    </div>
                    {% endfor %}
                </div>
            </div>

            {% if user_is_owner %}
                <form class="form-container" action="{% url 'card_create' board_id=board.id %}" method="get">
                    <button class="transparent-button">Create a card</button>
                </form>

                <div></div>

                <form class="form-container" method="post" action="">
                    {% csrf_token %}
                    <button class="transparent-button">Delete the board</button>
                </form>
            {% endif %}
        </section>

        <section class="members">
            <h2>Members</h2>

            <div class="scrollable">
                {% for member in board.membership_set.all %}
                    {% if member.user.username != user.username %}
                    <div class="member">
                        <p>{{ member.user.username }}</p>
                        {% if user_is_owner %}
                        <form action="{% url 'delete_member' board_id=board.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="member" value="{{ member.user.username }}">
                            <button class="delete-member-botton">Delete</button>
                        </form>
                        {% endif %}
                    </div>
                    {% endif %}
                {% endfor %}
            </div>

            {% if user_is_owner%}
                <div class="invite">
                    <form method="post" action="{% url 'сreate_invitation' board_id=board.id %}">
                        {% csrf_token %}
                        <label for="username">User:</label>
                        <input type="text" id="recipient" name="recipient" required>
                        <button class="transparent-button">Invite</button>
                    </form>
                </div>

                {% if messages %}
                    {% for message in messages %}
                        <p class="{{ message.tags }}-message">{{ message }}<p>
                    {% endfor %}
                {% endif %}
            {% endif %}
            
        </section>
    </main>
    <footer></footer>

</body>

</html>

thisapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

    <head>
        {% include 'includes/common_head.html' %}
        <link rel="stylesheet" type="text/css" href="{% static 'thisapp/css/index.css' %}">
        <title>KANBAN</title>
    </head>

    <body>
        <header>
            <form action="{% url 'signup' %}" method="get">
                <button class="transparent-button">Sign Up</button>
            </form>

            <h1>KANBAN</h1>

            <form action="{% url 'login' %}" method="get">
                <button class="transparent-button">Log in</button>
            </form>
        </header>

        <main>
            <img src="{% static 'thisapp/images/ninja.png' %}" alt="ninja programmer">
            <h2>A totally innovative service that allows you to organise your problem solving process.</h2>
            <p>Invite people to projects, organise discussions and solve problems together!</p>
        </main>

        <footer></footer>

    </body>

</html>

thisapp/templates/profile.html
<!DOCTYPE html>

<html lang="en">
    {% load static %}
    
    <head>
        {% include 'includes/common_head.html' %}
        <link rel="stylesheet" type="text/css" href="{% static 'thisapp/css/profile.css' %}">
        <title>{{ user.username }}`s profile</title>
    </head>
    
    <body>
        <header>
            <form action="{% url 'logout' %}" method="get">
                <button class="transparent-button">Log out</button>
            </form>
            
            {% if user.group.name == 'normal' %}
                <h2>{{ user.username }} ({{ user.email }})</h2>
            {% else %}
                <h2>{{ user.username }}</h2>
            {% endif %}

            {% if user.group.name == 'normal' %}
                <form action="{% url 'password_change' %}" method="get">
                    <button class="transparent-button">Change password</button>
                </form>
            {% else %}
                <span></span>
            {% endif %}
        </header>

        <main>

            {% if owner_boards %}
            <section>
                <h2>Your boards</h2>
                <div class="line-block">
                    {% for board in owner_boards %}
                    <form action="{% url 'board' board_id=board.id %}" method="get">
                        <button class="board-button">{{ board.title }}</button>
                    </form>
                    {% endfor %}
                </div>
            </section>
            {% endif %}

            <section>
                <h3>Create a new board</h3>
                <form method="post" action="{% url 'create_board' %}">
                    {% csrf_token %}
                    <div class="line-block">
                        {% for field in form %}
                            <p>
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                        {% endfor %}
                        <button class="transparent-button">Create</button>
                    </div>
                </form>
            </section>

            {% if invitations %}
            <section>
                <h2>Invitations</h2>
                {% for invitation in invitations %}
                <div class="line-block">
                    {{ invitation.sender_name }} invites you to "{{ invitation.board_title }}"
                    <form action="{% url 'pick_invitation' board_id=invitation.board_id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="operation" value="reject">
                        <button class="transparent-button" type="submit">Reject</button>
                    </form>
                    <form action="{% url 'pick_invitation' board_id=invitation.board_id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="operation" value="accept">
                        <button class="transparent-button" type="submit">Accept</button>
                    </form>
                </div>
                {% endfor %}
            </section>
            {% endif %}

            {% if invitation_boards %}
            <section>
                <h2>You're a member of</h2>
                <div class="line-block">
                    {% for board in invitation_boards %}
                    <form action="{% url 'board' board_id=board.id %}" method="get">
                        <button class="board-button">{{ board.title }}</button>
                    </form>
                    {% endfor %}
                </div>
            </section>
            {% endif %}

        </main>

        <footer></footer>
    </body>
</html>